global:
  scrape_interval: 5s # Fast updates for real-time monitoring
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'retail_ops_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000'] # Matches the service name in docker-compose
